import { Filter, Grid2X2, List, Plus, Search } from "lucide-react";

import { StudioButton, StudioEmptyState, StudioPageHeader } from "@/components/dashboard/studio-shell";
import { getArtworks } from "@/app/actions/artworks";

export default async function ArtworksPage() {
  const items = await getArtworks();
  return <div className="flex flex-col gap-8"><StudioPageHeader eyebrow="Catalogue" title="Artworks" description="Keep every work, detail, and movement in one considered archive." action={<StudioButton href="/studio/artworks/new"><Plus data-icon="inline-start" />Add artwork</StudioButton>} /><div className="flex flex-col gap-3 md:flex-row md:items-center"><div className="studio-card flex h-11 flex-1 items-center gap-3 px-3 text-sm text-studio-muted"><Search aria-hidden /><span>Search by title, medium, or catalogue number</span></div><button className="studio-card flex h-11 items-center justify-center gap-2 px-4 text-sm text-studio-muted"><Filter aria-hidden />Filters</button><div className="studio-card flex h-11 items-center gap-1 px-1"><button className="studio-icon-button text-studio-ink" aria-label="Grid view"><Grid2X2 /></button><button className="studio-icon-button" aria-label="List view"><List /></button></div></div>{items.length === 0 ? <div className="studio-card"><StudioEmptyState title="Your catalogue is waiting" description="There are no artworks in this workspace yet. Add a work to capture its image, story, materials, value, and history." action={<StudioButton href="/studio/artworks/new"><Plus data-icon="inline-start" />Add artwork</StudioButton>} /></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="studio-card flex flex-col gap-3 p-5"><div className="aspect-[4/3] bg-muted" /><p className="studio-eyebrow">{item.status}</p><h2 className="text-xl text-studio-ink">{item.title}</h2><p className="text-sm text-studio-muted">{[item.year, item.medium].filter(Boolean).join(" · ") || "Details to be added"}</p></article>)}</div>}</div>;
}
