"use client";

import { useActionState, useEffect, useState, useTransition } from "react";
import { FileCheck2, ShieldCheck } from "lucide-react";

import { IDLE } from "@/features/physical-wall/action-state";
import {
  previewAgreement,
  signAgreement,
} from "@/features/physical-wall/actions/agreement";
import {
  agreementClauses,
  TERMS_VERSION,
  type AgreementFacts,
} from "@/features/physical-wall/agreement";
import {
  Field,
  FormStatus,
  inputClass,
  SubmitButton,
} from "@/features/physical-wall/components/form-bits";

/**
 * Reading and signing the exhibition agreement (F20).
 *
 * The text is fetched from the server rather than assembled here, so what is
 * displayed is generated by the same function that produces the bytes we hash.
 * A preview built independently in the browser could drift from the stored
 * version, which would make the hash prove the wrong thing.
 *
 * The signature is the artist's own name, typed. It has to match the account —
 * checked on the server — because a signature that can be any string is not a
 * signature.
 */
export function AgreementPanel({
  bookingId,
  signedAt,
  termsHash,
}: {
  bookingId: string;
  signedAt: string | null;
  termsHash: string | null;
}) {
  const [state, action] = useActionState(signAgreement, IDLE);
  const [facts, setFacts] = useState<AgreementFacts | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [, startLoad] = useTransition();

  useEffect(() => {
    if (!open || facts) return;
    startLoad(async () => {
      const result = await previewAgreement(bookingId);
      if (result.ok) setFacts(result.facts);
      else setError(result.message);
    });
  }, [open, facts, bookingId]);

  if (signedAt) {
    return (
      <div className="border-hairline mt-5 border-t pt-5">
        <p className="text-signal flex items-center gap-2 text-sm font-medium">
          <FileCheck2 className="size-4" aria-hidden />
          Agreement signed on{" "}
          {new Date(signedAt).toLocaleDateString("en-IN", {
            day: "numeric",
            month: "long",
            year: "numeric",
          })}
        </p>
        {termsHash && (
          <p className="text-ink-muted mt-2 font-mono text-xs break-all">
            {termsHash}
          </p>
        )}
        <p className="text-ink-muted mt-2 text-xs leading-5">
          That hash is of the exact text you agreed to. Keep it — it is how the
          version you signed can be proven later.
        </p>
      </div>
    );
  }

  return (
    <div className="border-terracotta mt-5 border-t pt-5">
      <p className="text-sm leading-6">
        <strong>Sign the agreement to continue.</strong> You cannot book an
        install window, and the work cannot go on the wall, until this is
        signed.
      </p>

      {!open ? (
        <button
          type="button"
          onClick={() => setOpen(true)}
          className="border-hairline-strong hover:border-ink text-small mt-4 inline-flex h-10 items-center rounded-md border px-4"
        >
          Read and sign
        </button>
      ) : error ? (
        <p className="text-destructive mt-4 text-sm">{error}</p>
      ) : !facts ? (
        <p className="text-ink-muted mt-4 text-sm" aria-live="polite">
          Loading the agreement…
        </p>
      ) : (
        <form action={action} className="mt-4 flex flex-col gap-4">
          <input type="hidden" name="bookingId" value={bookingId} />

          <div className="border-hairline bg-band max-h-80 overflow-y-auto rounded-md border p-5 text-sm leading-7">
            <p className="text-ink font-medium">
              ARTWALL LABS — EXHIBITION AGREEMENT
            </p>
            <p className="text-ink-muted text-xs">
              Terms version {TERMS_VERSION} · booking {facts.bookingId}
            </p>
            {agreementClauses(facts).map((clause) => (
              <p key={clause.heading} className="mt-3">
                <strong className="text-ink">{clause.heading}</strong>{" "}
                <span className="text-ink-muted">{clause.body}</span>
              </p>
            ))}
          </div>

          <label className="flex cursor-pointer gap-3 text-sm leading-6">
            <input
              type="checkbox"
              name="agreed"
              required
              className="mt-1 size-4 shrink-0"
            />
            <span>
              I have read the agreement above and I sign it electronically.
            </span>
          </label>

          <Field
            label="Type your full name to sign"
            htmlFor={`sign-${bookingId}`}
            hint={`It has to match the name on your account: ${facts.artistName}.`}
          >
            <input
              id={`sign-${bookingId}`}
              name="signedName"
              required
              autoComplete="off"
              className={inputClass}
            />
          </Field>

          <div className="flex items-center gap-3">
            <SubmitButton>Sign</SubmitButton>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="text-ink-muted hover:text-ink text-small underline underline-offset-4"
            >
              Not now
            </button>
          </div>

          <FormStatus state={state} />

          <p className="text-ink-muted flex items-start gap-2 text-xs leading-5">
            <ShieldCheck className="mt-0.5 size-3.5 shrink-0" aria-hidden />
            We store the exact text and a SHA-256 of it. Valid under section 6 of
            the Information Technology Act, 2000.
          </p>
        </form>
      )}
    </div>
  );
}
